global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'load-emulator'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['load-emulator:8080']
