services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_NAME=etcd
      - ETCD_HEARTBEAT_INTERVAL=500
      - ETCD_ELECTION_TIMEOUT=2500
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 2s
      retries: 10
    networks:
      - patroni-network

  patroni1:
    build: .
    container_name: patroni1
    environment:
      PATRONI_SCOPE: pgcluster01
      PATRONI_NAME: pg-node-1
      SEED_COUNT: ${SEED_COUNT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ANALYST_NAMES: ${ANALYST_NAMES}
    volumes:
      - ./patroni/patroni1.yaml:/etc/patroni.yml
      - pgdata1:/var/lib/postgresql/data
    ports:
      - "5431:5432"
      - "8010:8010"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 2s
      timeout: 2s
      retries: 3
    depends_on:
      etcd:
        condition: service_healthy
    networks:
      - patroni-network
    extra_hosts:
      - "patroni1:172.26.0.3"
      - "patroni2:172.26.0.4"

  patroni2:
    build: .
    container_name: patroni2
    environment:
      - PATRONI_SCOPE=pgcluster01
      - PATRONI_NAME=pg-node-2
    volumes:
      - ./patroni/patroni2.yaml:/etc/patroni.yml
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "8011:8011"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    depends_on:
      etcd:
        condition: service_healthy
    networks:
      - patroni-network
    extra_hosts:
      - "patroni1:172.26.0.3"
      - "patroni2:172.26.0.4"

  haproxy:
    image: haproxy:2.7
    container_name: haproxy
    ports:
      - "5433:5433"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      patroni1:
        condition: service_healthy
      patroni2:
        condition: service_healthy
    networks:
      - patroni-network



networks:
  patroni-network:
    external: true
    name: shared-pg-network

volumes:
  pgdata1:
  pgdata2: